### ISSUE TITLE
Calling functions crashes

### ISSUE THREAD

**Issue by ehsan** [mozilla/spidernode#172]
```
$ ./node -e 'console.log("hello, world!")'
ASAN:DEADLYSIGNAL
=================================================================
==80566==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x0001003f77ca bp 0x7fff5fbfdc10 sp 0x7fff5fbfd880 T0)
    #0 0x1003f77c9 in v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) RootingAPI.h:668
    #1 0x10030b649 in node::MakeCallback(node::Environment*, v8::Local<v8::Value>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*) node.cc:1214
    #2 0x10031d841 in node::EmitBeforeExit(node::Environment*) node.cc:4297
    #3 0x10031e335 in node::Start(int, char**) node.cc:4427
    #4 0x7fff9a0905ac in start (libdyld.dylib+0x35ac)
    #5 0x2  (node)+0x2)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV RootingAPI.h:668 in v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*)
==80566==ABORTING
Abort trap: 6
```

I'll look into why tomorrow.  I've recently touched `Function::Call()`.

**Comment by ehsan** [comment]
#170 fixed this.
