### ISSUE TITLE
Crash when evaluating |this| in the REPL environment

### ISSUE THREAD

**Issue by ehsan** [mozilla/spidernode#175]
```
$ ./node
> this
ASAN:DEADLYSIGNAL
=================================================================
==26130==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000100434065 bp 0x7fff5fbd00b0 sp 0x7fff5fbcf8c0 T0)
    #0 0x100434064 in (anonymous namespace)::EnumeratorOp(JSContext*, JS::Handle<JSObject*>, JS::AutoVectorRooter<jsid>&, bool) v8.h:1884
    #1 0x101454aa5 in EnumerateExtraProperties(JSContext*, JS::Handle<JSObject*>, unsigned int, mozilla::Maybe<js::HashSet<jsid, IdHashPolicy, js::TempAllocPolicy> >&, JS::AutoVectorRooter<jsid>*) jsiter.cpp:139
    #2 0x101430a5e in Snapshot(JSContext*, JS::Handle<JSObject*>, unsigned int, JS::AutoVectorRooter<jsid>*) jsiter.cpp:376
    #3 0x101cc88cf in js::GetOwnPropertyKeys(JSContext*, JS::CallArgs const&, unsigned int) Object.cpp:852
    #4 0x101ce2187 in obj_keys(JSContext*, unsigned int, JS::Value*) Object.cpp:790
    #5 0x1018afde8 in js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct) jscntxtinlines.h:232
    #6 0x10189549c in Interpret(JSContext*, js::RunState&) Interpreter.cpp:504
    #7 0x101878b51 in js::RunScript(JSContext*, js::RunState&) Interpreter.cpp:399
    #8 0x1018b044c in js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct) Interpreter.cpp:471
    #9 0x100acaa60 in js::jit::DoCallFallback(JSContext*, js::jit::BaselineFrame*, js::jit::ICCall_Fallback*, unsigned int, JS::Value*, JS::MutableHandle<JS::Value>) BaselineIC.cpp:5977
    #10 0x1093fd745  (<unknown module>)
    #11 0x6210005e2d6f  (<unknown module>)
    #12 0x1093f6887  (<unknown module>)
    #13 0x100b3ba82 in EnterBaseline(JSContext*, js::jit::EnterJitData&) BaselineJIT.cpp:155
    #14 0x100b3cc9a in js::jit::EnterBaselineAtBranch(JSContext*, js::InterpreterFrame*, unsigned char*) BaselineJIT.cpp:262
    #15 0x1018a1887 in Interpret(JSContext*, js::RunState&) Interpreter.cpp:1877
    #16 0x101878b51 in js::RunScript(JSContext*, js::RunState&) Interpreter.cpp:399
    #17 0x1018b044c in js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct) Interpreter.cpp:471
    #18 0x101856912 in js::Call(JSContext*, JS::Handle<JS::Value>, JS::Handle<JS::Value>, js::AnyInvokeArgs const&, JS::MutableHandle<JS::Value>) Interpreter.cpp:517
    #19 0x1013c6cc8 in js::fun_apply(JSContext*, unsigned int, JS::Value*) jsfun.cpp:1327
    #20 0x1018afde8 in js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct) jscntxtinlines.h:232
    #21 0x10189549c in Interpret(JSContext*, js::RunState&) Interpreter.cpp:504
    #22 0x101878b51 in js::RunScript(JSContext*, js::RunState&) Interpreter.cpp:399
    #23 0x1018b044c in js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct) Interpreter.cpp:471
    #24 0x101856912 in js::Call(JSContext*, JS::Handle<JS::Value>, JS::Handle<JS::Value>, js::AnyInvokeArgs const&, JS::MutableHandle<JS::Value>) Interpreter.cpp:517
    #25 0x1013c54d2 in js::fun_call(JSContext*, unsigned int, JS::Value*) jsfun.cpp:1258
    #26 0x1018afde8 in js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct) jscntxtinlines.h:232
    #27 0x10189549c in Interpret(JSContext*, js::RunState&) Interpreter.cpp:504
    #28 0x101878b51 in js::RunScript(JSContext*, js::RunState&) Interpreter.cpp:399
    #29 0x1018b044c in js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct) Interpreter.cpp:471
    #30 0x100acaa60 in js::jit::DoCallFallback(JSContext*, js::jit::BaselineFrame*, js::jit::ICCall_Fallback*, unsigned int, JS::Value*, JS::MutableHandle<JS::Value>) BaselineIC.cpp:5977
    #31 0x1093fd745  (<unknown module>)
    #32 0x62100058064f  (<unknown module>)
    #33 0x1093f6887  (<unknown module>)
    #34 0x100b3ba82 in EnterBaseline(JSContext*, js::jit::EnterJitData&) BaselineJIT.cpp:155
    #35 0x100b3b1e4 in js::jit::EnterBaselineMethod(JSContext*, js::RunState&) BaselineJIT.cpp:194
    #36 0x1018994ad in Interpret(JSContext*, js::RunState&) Interpreter.cpp:2918
    #37 0x101878b51 in js::RunScript(JSContext*, js::RunState&) Interpreter.cpp:399
    #38 0x1018b044c in js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct) Interpreter.cpp:471
    #39 0x100acaa60 in js::jit::DoCallFallback(JSContext*, js::jit::BaselineFrame*, js::jit::ICCall_Fallback*, unsigned int, JS::Value*, JS::MutableHandle<JS::Value>) BaselineIC.cpp:5977
    #40 0x1093fd745  (<unknown module>)
    #41 0x6210005a05df  (<unknown module>)
    #42 0x1093f6887  (<unknown module>)
    #43 0x100b3ba82 in EnterBaseline(JSContext*, js::jit::EnterJitData&) BaselineJIT.cpp:155
    #44 0x100b3b1e4 in js::jit::EnterBaselineMethod(JSContext*, js::RunState&) BaselineJIT.cpp:194
    #45 0x1018994ad in Interpret(JSContext*, js::RunState&) Interpreter.cpp:2918
    #46 0x101878b51 in js::RunScript(JSContext*, js::RunState&) Interpreter.cpp:399
    #47 0x1018b044c in js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct) Interpreter.cpp:471
    #48 0x101856912 in js::Call(JSContext*, JS::Handle<JS::Value>, JS::Handle<JS::Value>, js::AnyInvokeArgs const&, JS::MutableHandle<JS::Value>) Interpreter.cpp:517
    #49 0x1013c54d2 in js::fun_call(JSContext*, unsigned int, JS::Value*) jsfun.cpp:1258
    #50 0x1018afde8 in js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct) jscntxtinlines.h:232
    #51 0x10189549c in Interpret(JSContext*, js::RunState&) Interpreter.cpp:504
    #52 0x101878b51 in js::RunScript(JSContext*, js::RunState&) Interpreter.cpp:399
    #53 0x1018b044c in js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct) Interpreter.cpp:471
    #54 0x100acaa60 in js::jit::DoCallFallback(JSContext*, js::jit::BaselineFrame*, js::jit::ICCall_Fallback*, unsigned int, JS::Value*, JS::MutableHandle<JS::Value>) BaselineIC.cpp:5977
    #55 0x1093fd745  (<unknown module>)
    #56 0x6210005807d7  (<unknown module>)
    #57 0x1093f6887  (<unknown module>)
    #58 0x100b3ba82 in EnterBaseline(JSContext*, js::jit::EnterJitData&) BaselineJIT.cpp:155
    #59 0x100b3b1e4 in js::jit::EnterBaselineMethod(JSContext*, js::RunState&) BaselineJIT.cpp:194
    #60 0x1018994ad in Interpret(JSContext*, js::RunState&) Interpreter.cpp:2918
    #61 0x101878b51 in js::RunScript(JSContext*, js::RunState&) Interpreter.cpp:399
    #62 0x1018b044c in js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct) Interpreter.cpp:471
    #63 0x100acaa60 in js::jit::DoCallFallback(JSContext*, js::jit::BaselineFrame*, js::jit::ICCall_Fallback*, unsigned int, JS::Value*, JS::MutableHandle<JS::Value>) BaselineIC.cpp:5977
    #64 0x1093fd745  (<unknown module>)
    #65 0x6210005ad0f7  (<unknown module>)
    #66 0x1093f6887  (<unknown module>)
    #67 0x100b3ba82 in EnterBaseline(JSContext*, js::jit::EnterJitData&) BaselineJIT.cpp:155
    #68 0x100b3b1e4 in js::jit::EnterBaselineMethod(JSContext*, js::RunState&) BaselineJIT.cpp:194
    #69 0x10187899f in js::RunScript(JSContext*, js::RunState&) Interpreter.cpp:389
    #70 0x1018b044c in js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct) Interpreter.cpp:471
    #71 0x101856912 in js::Call(JSContext*, JS::Handle<JS::Value>, JS::Handle<JS::Value>, js::AnyInvokeArgs const&, JS::MutableHandle<JS::Value>) Interpreter.cpp:517
    #72 0x1013c54d2 in js::fun_call(JSContext*, unsigned int, JS::Value*) jsfun.cpp:1258
    #73 0x1018afde8 in js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct) jscntxtinlines.h:232
    #74 0x10189549c in Interpret(JSContext*, js::RunState&) Interpreter.cpp:504
    #75 0x101878b51 in js::RunScript(JSContext*, js::RunState&) Interpreter.cpp:399
    #76 0x1018b044c in js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct) Interpreter.cpp:471
    #77 0x100acaa60 in js::jit::DoCallFallback(JSContext*, js::jit::BaselineFrame*, js::jit::ICCall_Fallback*, unsigned int, JS::Value*, JS::MutableHandle<JS::Value>) BaselineIC.cpp:5977
    #78 0x1093fd745  (<unknown module>)
    #79 0x62100058064f  (<unknown module>)
    #80 0x1093f6887  (<unknown module>)
    #81 0x100b3ba82 in EnterBaseline(JSContext*, js::jit::EnterJitData&) BaselineJIT.cpp:155
    #82 0x100b3b1e4 in js::jit::EnterBaselineMethod(JSContext*, js::RunState&) BaselineJIT.cpp:194
    #83 0x1018994ad in Interpret(JSContext*, js::RunState&) Interpreter.cpp:2918
    #84 0x101878b51 in js::RunScript(JSContext*, js::RunState&) Interpreter.cpp:399
    #85 0x1018b044c in js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct) Interpreter.cpp:471
    #86 0x101856912 in js::Call(JSContext*, JS::Handle<JS::Value>, JS::Handle<JS::Value>, js::AnyInvokeArgs const&, JS::MutableHandle<JS::Value>) Interpreter.cpp:517
    #87 0x101304d98 in JS::Call(JSContext*, JS::Handle<JS::Value>, JS::Handle<JS::Value>, JS::HandleValueArray const&, JS::MutableHandle<JS::Value>) jsapi.cpp:2852
    #88 0x1003f8bf4 in v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) v8function.cc:256
    #89 0x1002ecd5a in node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) async-wrap.cc:238
    #90 0x100382cee in node::StreamBase::EmitData(long, v8::Local<v8::Object>, v8::Local<v8::Object>) async-wrap-inl.h:110
    #91 0x100387ed6 in node::StreamWrap::OnReadImpl(long, uv_buf_t const*, uv_handle_type, void*) stream_wrap.cc:222
    #92 0x1003891cd in node::StreamWrap::OnReadCommon(uv_stream_s*, long, uv_buf_t const*, uv_handle_type) stream_base.h:171
    #93 0x1004d7f27 in uv__stream_io stream.c:1192
    #94 0x1004ef73e in uv__io_poll kqueue.c:276
    #95 0x1004be0fc in uv_run core.c:354
    #96 0x10031e928 in node::Start(int, char**) node.cc:4423
    #97 0x7fff9a0905ac in start (libdyld.dylib+0x35ac)
    #98 0x0  (+0x0)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV v8.h:1884 in (anonymous namespace)::EnumeratorOp(JSContext*, JS::Handle<JSObject*>, JS::AutoVectorRooter<jsid>&, bool)
==26130==ABORTING
Abort trap: 6
```

**Comment by ehsan** [comment]
Should be fixed on master now.
