### ISSUE TITLE
various tests throw: TypeError: invalid arguments

### ISSUE THREAD

**Issue by mykmelez** [mozilla/spidernode#223]
>=== release test-buffer-alloc ===                            
>Path: parallel/test-buffer-alloc
>JS error at buffer.js:160: TypeError: invalid arguments
>buffer.js:160
>
>
>
>TypeError: invalid arguments
>    at Buffer.alloc (buffer.js:160:10)
>    at /Users/myk/Projects/spidernode/test/parallel/test-buffer-alloc.js:715:1
>    at Module.prototype._compile (module.js:560:16)
>    at Module._extensions[".js"] (module.js:569:3)
>    at Module.prototype.load (module.js:477:3)
>    at tryModuleLoad (module.js:436:5)
>    at Module._load (module.js:428:3)
>    at Module.runMain (module.js:594:3)
>    at run (bootstrap_node.js:382:7)
>    at startup (bootstrap_node.js:137:9)
>    at bootstrap_node.js:497:3
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-buffer-alloc.js
>--- CRASHED (Signal: 11) ---

**Comment by tbsaunde** [comment]
On Wed, Dec 14, 2016 at 01:42:11PM -0800, Myk Melez wrote:
>     === release test-buffer-alloc ===
>     Path: parallel/test-buffer-alloc
>     JS error at buffer.js:160: TypeError: invalid arguments
>     buffer.js:160

This is a spidermonkey bug where its array buffer ctor is not to spec in
how it handles some arguments.  Chakra has a similar problem with this
one, and handles it by changing the test slightly to expect different
things, but fixing spidermonkey seems better.

I can't track down the spidermonkey bug right now, but I've definitely
seen it.

**Comment by mykmelez** [comment]
test-fs-read-buffer-tostring-fail and test-fs-readfile-tostring-fail are also hit by this issue.

**Comment by mykmelez** [comment]
This is still a problem, although the line on which it occurs has changed:

```sh
> tools/test.py parallel/test-buffer-alloc.js
=== release test-buffer-alloc ===                    
Path: parallel/test-buffer-alloc
JS error at buffer.js:33: TypeError: invalid arguments
buffer.js:33
```

**Comment by mykmelez** [comment]
test-child-process-send-after-close and test-child-process-spawnsync-input are failing with the same error.

**Comment by mykmelez** [comment]
test-repl-underscore does this too.

**Comment by mykmelez** [comment]
So does test-net-pipe-connect-errors.
