### ISSUE TITLE
test scripts that check the value of a process exit code assert null == 0 or something similar

### ISSUE THREAD

**Issue by mykmelez** [mozilla/spidernode#226]
Three of the test-child-process-* tests—exit-code, fork-and-spawn, and fork-exec-path—check the exit code of a process they start and assert because it's `null` rather than the number they expect.

>=== release test-child-process-exit-code ===                                   
>Path: parallel/test-child-process-exit-code
>:0
>
>
>AssertionError: null === 23
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-child-process-exit-code.js
>--- CRASHED (Signal: 11) ---
>=== release test-child-process-fork-and-spawn ===                    
>Path: parallel/test-child-process-fork-and-spawn
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>
>:0
>
>
>AssertionError: null == 0
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-child-process-fork-and-spawn.js
>--- CRASHED (Signal: 11) ---
>=== release test-child-process-fork-exec-path ===                    
>Path: parallel/test-child-process-fork-exec-path
>dyld: Library not loaded: @executable_path/libmozglue.dylib
>  Referenced from: /Users/myk/Projects/spidernode/test/tmp.0/node-copy.exe
>  Reason: image not found
>
>:0
>
>
>AssertionError: null == 0
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-child-process-fork-exec-path.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
test-child-process-spawnsync also asserts because "exit status should be zero", which seems likely to have the same root cause:

>=== release test-child-process-spawnsync ===                          
>Path: parallel/test-child-process-spawnsync
>JS error at <no filename>:0: uncaught exception: AssertionError: exit status should be zero
>
>:0
>
>
>AssertionError: exit status should be zero
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-child-process-spawnsync.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
test-cluster-shared-handle-bind-error and test-cluster-shared-handle-bind-privileged-port are also affected:
>=== release test-cluster-shared-handle-bind-error ===                    
>Path: parallel/test-cluster-shared-handle-bind-error
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>
>:0
>
>
>AssertionError: null == 0
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-cluster-shared-handle-bind-error.js
>--- CRASHED (Signal: 11) ---
>=== release test-cluster-shared-handle-bind-privileged-port ===                
>Path: parallel/test-cluster-shared-handle-bind-privileged-port
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>
>:0
>
>
>AssertionError: null == 0
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-cluster-shared-handle-bind-privileged-port.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
>=== release test-cluster-uncaught-exception ===                               
>Path: parallel/test-cluster-uncaught-exception
>JS error at /Users/myk/Projects/spidernode/test/parallel/test-cluster-uncaught-exception.js:28: Error: kill master
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>
>:0
>
>
>AssertionError: null === 42
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-cluster-uncaught-exception.js
>--- CRASHED (Signal: 11) ---
>=== release test-cluster-worker-death ===                          
>Path: parallel/test-cluster-worker-death
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>
>:0
>
>
>AssertionError: null == 42
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-cluster-worker-death.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
>=== release test-cluster-worker-events ===                                 
>Path: parallel/test-cluster-worker-events
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>
>:0
>
>
>AssertionError: null == 2
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-cluster-worker-events.js
>--- CRASHED (Signal: 11) ---
…
>=== release test-cluster-worker-forced-exit ===                    
>Path: parallel/test-cluster-worker-forced-exit
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>
>:0
>
>
>AssertionError: null === 0
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-cluster-worker-forced-exit.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
>=== release test-cwd-enoent-repl ===                            
>Path: parallel/test-cwd-enoent-repl
>> { resolve: [Function: resolve],
>  normalize: [Function: normalize],
>  isAbsolute: [Function: isAbsolute],
>  join: [Function: join],
>  relative: [Function: relative],
>  _makeLong: [Function: _makeLong],
>  dirname: [Function: dirname],
>  basename: [Function: basename],
>  extname: [Function: extname],
>  format: [Function: format],
>  parse: [Function: parse],
>  sep: '/',
>  delimiter: ':',
>  win32: 
>   { resolve: [Function: resolve],
>     normalize: [Function: normalize],
>     isAbsolute: [Function: isAbsolute],
>     join: [Function: join],
>     relative: [Function: relative],
>     _makeLong: [Function: _makeLong],
>     dirname: [Function: dirname],
>     basename: [Function: basename],
>     extname: [Function: extname],
>     format: [Function: format],
>     parse: [Function: parse],
>     sep: '\\',
>     delimiter: ';',
>     win32: [Circular],
>     posix: [Circular] },
>  posix: [Circular] }
>>
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>
>:0
>
>
>AssertionError: null == 42
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-cwd-enoent-repl.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
>=== release test-debug-brk-no-arg ===                    
>Path: parallel/test-debug-brk-no-arg
>:0
>
>
>AssertionError: null === 0
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-debug-brk-no-arg.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
>=== release test-debug-uncaught-exception ===                    
>Path: parallel/test-debug-uncaught-exception
>JS error at <no filename>:0: uncaught exception: AssertionError: 0 === 1
>
>:0
>
>
>AssertionError: 0 === 1
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-debug-uncaught-exception.js
>--- CRASHED (Signal: 11) ---
>=== release test-debug-usage ===                                
>Path: parallel/test-debug-usage
>:0
>
>
>AssertionError: null === 1
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-debug-usage.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
>=== release test-domain-abort-on-uncaught ===                    
>Path: parallel/test-domain-abort-on-uncaught
>:0
>
>
>AssertionError: Test at index 0 should have exited with exit code 0 but instead exited with code 9 and signal null
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-domain-abort-on-uncaught.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
>=== release test-domain-top-level-error-handler-throw ===                      
>Path: parallel/test-domain-top-level-error-handler-throw
>:0
>
>
>AssertionError: null == 7
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-domain-top-level-error-handler-throw.js
>--- CRASHED (Signal: 11) ---
>=== release test-domain-with-abort-on-uncaught-exception ===                   
>Path: parallel/test-domain-with-abort-on-uncaught-exception
>:0
>
>
>AssertionError: 9 == 0
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-domain-with-abort-on-uncaught-exception.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
This seems like a duplicate, although it's strange that some of the exit code checks in the test script succeed, as I've been expecting all such checks to fail:

>=== release test-process-exit-code ===                    
>Path: parallel/test-process-exit-code
>ok - child1 exited with 42
>ok - child5 exited with 99
>:0
>
>
>AssertionError: wrong exit for child4
>expected:1 but got:null
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-process-exit-code.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
>=== release test-repl-sigint ===                                
>Path: parallel/test-repl-sigint
>>
>a = 1001;process.kill(+process.env.REPL_TEST_PPID, "SIGUSR2");while(true){}
>JS warning at repl:1: Script terminated by timeout at:
>    at repl:1:74
>    at Script.prototype.runInThisContext/< (vm.js:22:14)
>    at sigintHandlersWrap (vm.js:96:12)
>    at Script.prototype.runInThisContext (vm.js:21:12)
>    at defaultEval (repl.js:313:22)
>    at bound (domain.js:280:11)
>    at runBound (domain.js:293:12)
>    at REPLServer/< (repl.js:513:5)
>    at emitOne (events.js:96:5)
>    at emit (events.js:188:7)
>    at Interface.prototype._onLine (readline.js:233:5)
>    at Interface.prototype._normalWrite/< (readline.js:369:7)
>    at Interface.prototype._normalWrite (readline.js:368:5)
>    at ondata (readline.js:101:5)
>    at emitOne (events.js:96:5)
>    at emit (events.js:188:7)
>    at readableAddChunk (_stream_readable.js:176:11)
>    at Readable.prototype.push (_stream_readable.js:134:10)
>    at onread (net.js:543:15)
>
>:0
>
>
>AssertionError: null === 0
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-repl-sigint.js
>--- CRASHED (Signal: 11) ---
>=== release test-repl-sigint-nested-eval ===                    
>Path: parallel/test-repl-sigint-nested-eval
>>
>process.kill(+process.env.REPL_TEST_PPID, "SIGUSR2");vm.runInThisContext("while(true){}", { breakOnSigint: true });
>JS warning at vm.js:76: Script terminated by timeout at:
>    at exports.runInThisContext (vm.js:76:16)
>    at repl:1:54
>    at Script.prototype.runInThisContext/< (vm.js:22:14)
>    at sigintHandlersWrap (vm.js:96:12)
>    at Script.prototype.runInThisContext (vm.js:21:12)
>    at defaultEval (repl.js:313:22)
>    at bound (domain.js:280:11)
>    at runBound (domain.js:293:12)
>    at REPLServer/< (repl.js:513:5)
>    at emitOne (events.js:96:5)
>    at emit (events.js:188:7)
>    at Interface.prototype._onLine (readline.js:233:5)
>    at Interface.prototype._normalWrite/< (readline.js:369:7)
>    at Interface.prototype._normalWrite (readline.js:368:5)
>    at ondata (readline.js:101:5)
>    at emitOne (events.js:96:5)
>    at emit (events.js:188:7)
>    at readableAddChunk (_stream_readable.js:176:11)
>    at Readable.prototype.push (_stream_readable.js:134:10)
>    at onread (net.js:543:15)
>
>:0
>
>
>AssertionError: null === 0
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-repl-sigint-nested-eval.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
>=== release test-stdout-cannot-be-closed-child-process-pipe ===                
>Path: parallel/test-stdout-cannot-be-closed-child-process-pipe
>:0
>
>
>AssertionError: null == true
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-stdout-cannot-be-closed-child-process-pipe.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
A bunch of these test failures have now been fixed, while others remain, so I'm going to close this issue and open new ones for the remaining test failures.
