### ISSUE TITLE
test-child-process-spawnsync-timeout asserts: false == true

### ISSUE THREAD

**Issue by mykmelez** [mozilla/spidernode#231]
>=== release test-child-process-spawnsync-timeout ===                    
>Path: parallel/test-child-process-spawnsync-timeout
>{ error: 
>   { Error: spawnSync /Users/myk/Projects/spidernode/out/Release/node ETIMEDOUT
>       at exports._errnoException (util.js:1036:11)
>       at spawnSync (child_process.js:466:20)
>       at /Users/myk/Projects/spidernode/test/parallel/test-child-process-spawnsync-timeout.js:19:15
>       at Module.prototype._compile (module.js:560:16)
>       at Module._extensions[".js"] (module.js:569:3)
>       at Module.prototype.load (module.js:477:3)
>       at tryModuleLoad (module.js:436:5)
>       at Module._load (module.js:428:3)
>       at Module.runMain (module.js:594:3)
>       at run (bootstrap_node.js:382:7)
>       at startup (bootstrap_node.js:137:9)
>       at bootstrap_node.js:497:3
>     code: 'ETIMEDOUT',
>     errno: 'ETIMEDOUT',
>     syscall: 'spawnSync /Users/myk/Projects/spidernode/out/Release/node',
>     path: '/Users/myk/Projects/spidernode/out/Release/node',
>     spawnargs: 
>      [ '/Users/myk/Projects/spidernode/test/parallel/test-child-process-spawnsync-timeout.js',
>        'child' ] },
>  status: 0,
>  signal: 'SIGSEGV',
>  output: 
>   [ null,
>     <Buffer >,
>     <Buffer 2f 55 73 65 72 73 2f 6d 79 6b 2f 50 72 6f 6a 65 63 74 73 2f 73 70 69 64 65 72 6e 6f 64 65 2f 6f 75 74 2f 52 65 6c 65 61 73 65 2f 6e 6f 64 65 5b 39 32 ... > ],
>  pid: 92657,
>  stdout: <Buffer >,
>  stderr: <Buffer 2f 55 73 65 72 73 2f 6d 79 6b 2f 50 72 6f 6a 65 63 74 73 2f 73 70 69 64 65 72 6e 6f 64 65 2f 6f 75 74 2f 52 65 6c 65 61 73 65 2f 6e 6f 64 65 5b 39 32 ... >,
>  envPairs: 
>   [ … ],
>  options: 
>   { timeout: 200,
>     file: '/Users/myk/Projects/spidernode/out/Release/node',
>     args: 
>      [ '/Users/myk/Projects/spidernode/out/Release/node',
>        '/Users/myk/Projects/spidernode/test/parallel/test-child-process-spawnsync-timeout.js',
>        'child' ],
>     envPairs: 
>      [ … ],
>     stdio: [ [Object], [Object], [Object] ] },
>  args: 
>   [ '/Users/myk/Projects/spidernode/out/Release/node',
>     '/Users/myk/Projects/spidernode/test/parallel/test-child-process-spawnsync-timeout.js',
>     'child' ],
>  file: '/Users/myk/Projects/spidernode/out/Release/node' }
>JS error at <no filename>:0: uncaught exception: AssertionError: false == true
>
>:0
>
>
>AssertionError: false == true
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-child-process-spawnsync-timeout.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
Now works for me.
