### ISSUE TITLE
test-cli-eval asserts: '' == '[ \'--use-strict\', \'-p\', \'process.execArgv\' ]\n'

### ISSUE THREAD

**Issue by mykmelez** [mozilla/spidernode#233]
>=== release test-cli-eval ===                                          
>Path: parallel/test-cli-eval
>:0
>
>
>AssertionError: '' == '[ \'--use-strict\', \'-p\', \'process.execArgv\' ]\n'
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-cli-eval.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
This now reports:

>=== release test-cli-eval ===                    
>Path: parallel/test-cli-eval
>child_process.js:246
>
>
>Error: Command failed: "/Users/myk/Projects/spidernode/out/Release/node" --use-strict -p process.execArgv
>invalid argument --use-strict
>/Users/myk/Projects/spidernode/out/Release/node: bad option: --use-strict
>
>    at exithandler (child_process.js:246:12)
>    at emitTwo (events.js:125:5)
>    at emit (events.js:213:7)
>    at maybeClose (internal/child_process.js:893:5)
>    at ChildProcess.prototype.spawn/< (internal/child_process.js:335:11)
>    at emitOne (events.js:115:5)
>    at emit (events.js:210:7)
>    at Socket.prototype._destroy/< (net.js:530:7)
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-cli-eval.js
