### ISSUE TITLE
test-cluster-server-restart-rr asserts: worker1 did not exit normally after Error: bind EADDRINUSE

### ISSUE THREAD

**Issue by mykmelez** [mozilla/spidernode#247]
>=== release test-cluster-server-restart-rr ===                     
>Path: parallel/test-cluster-server-restart-rr
>util.js:1036
>
>
>Error: bind EADDRINUSE null:12346
>    at exports._errnoException (util.js:1036:11)
>    at exports._exceptionWithHostPort (util.js:1059:12)
>    at cb (net.js:1317:16)
>    at rr (cluster.js:627:14)
>    at workerInit/cluster._getServer/< (cluster.js:596:9)
>    at internal/< (cluster.js:767:5)
>    at emitTwo (events.js:111:7)
>    at emit (events.js:191:7)
>    at handleMessage/< (internal/child_process.js:744:5)
>    at _combinedTickCallback (internal/process/next_tick.js:67:7)
>    at _tickCallback (internal/process/next_tick.js:98:9)
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>
>:0
>
>
>AssertionError: worker1 did not exit normally
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-cluster-server-restart-rr.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
Now works for me.
