### ISSUE TITLE
test-debug-brk throws: Mismatched <anonymous> function calls. Expected 1, actual 0.

### ISSUE THREAD

**Issue by mykmelez** [mozilla/spidernode#253]
>=== release test-debug-brk ===                    
>Path: parallel/test-debug-brk
>Mismatched <anonymous> function calls. Expected 1, actual 0.
>    at /Users/myk/Projects/spidernode/test/parallel/test-debug-brk.js:21:17
>    at Module.prototype._compile (module.js:560:16)
>    at Module._extensions[".js"] (module.js:569:3)
>    at Module.prototype.load (module.js:477:3)
>    at tryModuleLoad (module.js:436:5)
>    at Module._load (module.js:428:3)
>    at Module.runMain (module.js:594:3)
>    at run (bootstrap_node.js:382:7)
>    at startup (bootstrap_node.js:137:9)
>    at bootstrap_node.js:497:3
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-debug-brk.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
This is still happening, although the line numbers have changed:

>=== release test-debug-brk ===                    
>Path: parallel/test-debug-brk
>Mismatched <anonymous> function calls. Expected 1, actual 0.
>    at run (/Users/myk/Projects/spidernode/test/parallel/test-debug-brk.js:39:21)
>    at /Users/myk/Projects/spidernode/test/parallel/test-debug-brk.js:70:1
>    at Module.prototype._compile (module.js:585:16)
>    at Module._extensions[".js"] (module.js:595:3)
>    at Module.prototype.load (module.js:503:3)
>    at tryModuleLoad (module.js:466:5)
>    at Module._load (module.js:458:3)
>    at Module.runMain (module.js:620:3)
>    at run (bootstrap_node.js:437:7)
>    at startup (bootstrap_node.js:147:9)
>    at bootstrap_node.js:552:3
>Mismatched <anonymous> function calls. Expected 1, actual 0.
>    at run (/Users/myk/Projects/spidernode/test/parallel/test-debug-brk.js:39:21)
>    at run/< (/Users/myk/Projects/spidernode/test/parallel/test-debug-brk.js:61:7)
>    at emitTwo (events.js:125:5)
>    at emit (events.js:213:7)
>    at ChildProcess/this._handle.onexit (internal/child_process.js:208:7)
>Mismatched <anonymous> function calls. Expected 1, actual 0.
>    at run (/Users/myk/Projects/spidernode/test/parallel/test-debug-brk.js:39:21)
>    at run/< (/Users/myk/Projects/spidernode/test/parallel/test-debug-brk.js:61:7)
>    at emitTwo (events.js:125:5)
>    at emit (events.js:213:7)
>    at ChildProcess/this._handle.onexit (internal/child_process.js:208:7)
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-debug-brk.js
