### ISSUE TITLE
test-debug-port-numbers times out after throwing TypeError: Debug.setBreakPoint is not a function

### ISSUE THREAD

**Issue by mykmelez** [mozilla/spidernode#256]
>=== release test-debug-port-numbers ===                        
>Path: parallel/test-debug-port-numbers
>debug> debug> debug> debug>< Debugger listening on 127.0.0.1:12346
>debug>connecting to 127.0.0.1:12346 ..< Debugger listening on 127.0.0.1:12347
>debug>connecting to 127.0.0.1:12347 ... ok
>< Debugger listening on 127.0.0.1:12348
>debug>connecting to 127.0.0.1:12348 ... ok
>< Debugger listening on 127.0.0.1:12349
>debug>connecting to 127.0.0.1:12349 ... ok
> ok
>< module.js:552
>< TypeError: Debug.setBreakPoint is not a function
><     at Module.prototype._compile (module.js:552:7)
><     at Module._extensions[".js"] (module.js:569:3)
><     at Module.prototype.load (module.js:477:3)
><     at tryModuleLoad (module.js:436:5)
><     at Module._load (module.js:428:3)
><     at Module.runMain (module.js:594:3)
><     at tryOnTimeout (timers.js:232:5)
><     at listOnTimeout (timers.js:202:5)
>< Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>< module.js:552
>< TypeError: Debug.setBreakPoint is not a function
><     at Module.prototype._compile (module.js:552:7)
><     at Module._extensions[".js"] (module.js:569:3)
><     at Module.prototype.load (module.js:477:3)
><     at tryModuleLoad (module.js:436:5)
><     at Module._load (module.js:428:3)
><     at Module.runMain (module.js:594:3)
><     at tryOnTimeout (timers.js:232:5)
><     at listOnTimeout (timers.js:202:5)debug> 
>debug>< Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>debug>< module.js:552
>< TypeError: Debug.setBreakPoint is not a function
><     at Module.prototype._compile (module.js:552:7)
><     at Module._extensions[".js"] (module.js:569:3)
><     at Module.prototype.load (module.js:477:3)
><     at tryModuleLoad (module.js:436:5)
><     at Module._load (module.js:428:3)
><     at Module.runMain (module.js:594:3)
><     at tryOnTimeout (timers.js:232:5)
><     at listOnTimeout (timers.js:202:5)
>< Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>debug>< module.js:552
>< TypeError: Debug.setBreakPoint is not a function
><     at Module.prototype._compile (module.js:552:7)
><     at Module._extensions[".js"] (module.js:569:3)
><     at Module.prototype.load (module.js:477:3)
><     at tryModuleLoad (module.js:436:5)
><     at Module._load (module.js:428:3)
><     at Module.runMain (module.js:594:3)
><     at tryOnTimeout (timers.js:232:5)
><     at listOnTimeout (timers.js:202:5)
>< Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>debug>program terminated
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-debug-port-numbers.js
>--- TIMEOUT ---

**Comment by mykmelez** [comment]
Still happening, with the same stacks, although at different line numbers:

>=== release test-debug-port-numbers ===                    
>Path: parallel/test-debug-port-numbers
>debug> debug> debug> debug>< (node:46377) [DEP0062] DeprecationWarning: node --debug is deprecated. Please use node --inspect instead.
>debug>connecting to 127.0.0.1:12346 ..< Debugger listening on 127.0.0.1:12346
>debug>  ok
>debug>< (node:46380) [DEP0062] DeprecationWarning: node --debug is deprecated. Please use node --inspect instead.
>debug>connecting to 127.0.0.1:12347 ..< (node:46378) [DEP0062] DeprecationWarning: node --debug is deprecated. Please use node --inspect instead.
>debug>connecting to 127.0.0.1:12348 ..< Debugger listening on 127.0.0.1:12347
>debug>< Debugger listening on 127.0.0.1:12348
>debug>< (node:46379) [DEP0062] DeprecationWarning: node --debug is deprecated. Please use node --inspect instead.
>debug>connecting to 127.0.0.1:12349 ... ok
>debug>  ok
>debug>< Debugger listening on 127.0.0.1:12349
>debug>  ok
>debug>< module.js:578
>< TypeError: Debug.setBreakPoint is not a function
><     at Module.prototype._compile (module.js:578:7)
><     at Module._extensions[".js"] (module.js:595:3)
><     at Module.prototype.load (module.js:503:3)
><     at tryModuleLoad (module.js:466:5)
><     at Module._load (module.js:458:3)
><     at Module.runMain (module.js:620:3)
><     at ontimeout (timers.js:407:5)
><     at tryOnTimeout (timers.js:271:5)
><     at listOnTimeout (timers.js:235:5)
>debug>program terminated
>debug>< module.js:578
>< TypeError: Debug.setBreakPoint is not a function
><     at Module.prototype._compile (module.js:578:7)
><     at Module._extensions[".js"] (module.js:595:3)
><     at Module.prototype.load (module.js:503:3)
><     at tryModuleLoad (module.js:466:5)
><     at Module._load (module.js:458:3)
><     at Module.runMain (module.js:620:3)
><     at ontimeout (timers.js:407:5)
><     at tryOnTimeout (timers.js:271:5)
><     at listOnTimeout (timers.js:235:5)
>debug>< module.js:578
>< TypeError: Debug.setBreakPoint is not a function
><     at Module.prototype._compile (module.js:578:7)
><     at Module._extensions[".js"] (module.js:595:3)
><     at Module.prototype.load (module.js:503:3)
><     at tryModuleLoad (module.js:466:5)
><     at Module._load (module.js:458:3)
><     at Module.runMain (module.js:620:3)
><     at ontimeout (timers.js:407:5)
><     at tryOnTimeout (timers.js:271:5)
><     at listOnTimeout (timers.js:235:5)
>debug>program terminated
>debug>program terminated
>debug>< module.js:578
>< TypeError: Debug.setBreakPoint is not a function
><     at Module.prototype._compile (module.js:578:7)
><     at Module._extensions[".js"] (module.js:595:3)
><     at Module.prototype.load (module.js:503:3)
><     at tryModuleLoad (module.js:466:5)
><     at Module._load (module.js:458:3)
><     at Module.runMain (module.js:620:3)
><     at ontimeout (timers.js:407:5)
><     at tryOnTimeout (timers.js:271:5)
><     at listOnTimeout (timers.js:235:5)
>debug>program terminated
>debug>
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-debug-port-numbers.js
>--- TIMEOUT ---
