### ISSUE TITLE
test-debug-signal-cluster asserts: test timed out; after Error: listen EADDRINUSE 127.0.0.1:12346

### ISSUE THREAD

**Issue by mykmelez** [mozilla/spidernode#257]
>=== release test-debug-signal-cluster ===                    
>Path: parallel/test-debug-signal-cluster
>> all workers are running
>> Starting debugger agent.
>> Error: listen EADDRINUSE 127.0.0.1:12346
>>     at exports._errnoException (util.js:1036:11)
>>     at exports._exceptionWithHostPort (util.js:1059:12)
>>     at Server.prototype._listen2 (net.js:1252:14)
>>     at listen (net.js:1288:5)
>>     at listenAfterLookup/< (net.js:1398:9)
>>     at _combinedTickCallback (internal/process/next_tick.js:77:11)
>>     at _tickCallback (internal/process/next_tick.js:98:9)
>got pids [93290,93291,93292]
>
>:0
>
>
>AssertionError: test timed out
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-debug-signal-cluster.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
Now works for me.
