### ISSUE TITLE
test-domain throws: TypeError: stat is undefined

### ISSUE THREAD

**Issue by mykmelez** [mozilla/spidernode#261]
>=== release test-domain ===                                               
>Path: parallel/test-domain
>caught emitted
>caught bound
>JS error at /Users/myk/Projects/spidernode/test/parallel/test-domain.js:125: Error: nextTick execution loop
>caught nextTick execution loop
>caught implicit timer
>caught ENOENT: no such file or directory, open 'this file does not exist'
>caught ENOENT: no such file or directory, open 'stream for nonexistent file'
>caught stat is undefined
>unexpected error, throwing "stat is undefined" { TypeError: stat is undefined
>    at i</</< (/Users/myk/Projects/spidernode/test/parallel/test-domain.js:143:11)
>    at makeCallback/< (fs.js:97:12)
>  domain: 
>   Domain {
>     domain: null,
>     _events: { error: [Function] },
>     _eventsCount: 1,
>     _maxListeners: undefined,
>     members: [ [Object], [Object] ] },
>  domainThrown: true }
>/Users/myk/Projects/spidernode/test/parallel/test-domain.js:143
>
>
>
>TypeError: stat is undefined
>    at i</</< (/Users/myk/Projects/spidernode/test/parallel/test-domain.js:143:11)
>    at makeCallback/< (fs.js:97:12)
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-domain.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
Still happening, with slightly different line numbers, and some additional output:

>=== release test-domain ===                    
>Path: parallel/test-domain
>adding cb function runIntercepted() {
>    return intercepted(this, self, cb, arguments);
>  }
>adding cb function(er, fd) {
>    if (er) {
>      if (self.autoClose) {
>        self.destroy();
>      }
>      self.emit('error', er);
>      return;
>    }
>
>    self.fd = fd;
>    self.emit('open', fd);
>    // start the flow of data.
>    self.read();
>  }
>[Function: runIntercepted]
>{ '0': 
>   { Error: ENOENT: no such file or directory, open 'this file does not exist'
>   
>     errno: -2,
>     code: 'ENOENT',
>     syscall: 'open',
>     path: 'this file does not exist' } }
>[Function]
>{ '0': 
>   { Error: ENOENT: no such file or directory, open 'stream for nonexistent file'
>   
>     errno: -2,
>     code: 'ENOENT',
>     syscall: 'open',
>     path: 'stream for nonexistent file' } }
>undefined
>caught emitted
>caught bound
>JS error at /Users/myk/Projects/spidernode/test/parallel/test-domain.js:147: Error: nextTick execution loop
>caught nextTick execution loop
>caught implicit timer
>caught ENOENT: no such file or directory, open 'this file does not exist'
>caught ENOENT: no such file or directory, open 'stream for nonexistent file'
>caught implicit
>caught stat is undefined
>unexpected error, throwing "stat is undefined" { TypeError: stat is undefined
>    at i</</< (/Users/myk/Projects/spidernode/test/parallel/test-domain.js:166:11)
>    at makeStatsCallback/< (fs.js:156:21)
>  domain: 
>   Domain {
>     domain: null,
>     _events: { error: [Function] },
>     _eventsCount: 1,
>     _maxListeners: undefined,
>     members: [ [Object], [Object] ] },
>  domainThrown: true }
>/Users/myk/Projects/spidernode/test/parallel/test-domain.js:166
>
>
>
>TypeError: stat is undefined
>    at i</</< (/Users/myk/Projects/spidernode/test/parallel/test-domain.js:166:11)
>    at makeStatsCallback/< (fs.js:156:21)
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-domain.js
