### ISSUE TITLE
test-preload reports: invalid argument --expose_debug_as=v8debug

### ISSUE THREAD

**Issue by mykmelez** [mozilla/spidernode#268]
>=== release test-preload ===                                             
>Path: parallel/test-preload
>child_process.js:211
>
>
>Error: Command failed: /Users/myk/Projects/spidernode/out/Release/node --expose_debug_as=v8debug --require /Users/myk/Projects/spidernode/test/fixtures/cluster-preload.js cluster-preload-test.js
>invalid argument --expose_debug_as=v8debug
>/Users/myk/Projects/spidernode/out/Release/node: bad option: --expose_debug_as=v8debug
>
>    at exithandler (child_process.js:211:12)
>    at emitTwo (events.js:106:5)
>    at emit (events.js:191:7)
>    at maybeClose (internal/child_process.js:877:5)
>    at ChildProcess.prototype.spawn/</< (internal/child_process.js:334:11)
>    at emitOne (events.js:96:5)
>    at emit (events.js:188:7)
>    at Socket.prototype._destroy/< (net.js:493:7)
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-preload.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
This now fails with the same error as #267:

>=== release test-preload ===                    
>Path: parallel/test-preload
>child_process.js:246
>
>
>Error: Command failed: /Users/myk/Projects/spidernode/out/Release/node --expose_natives_as=v8natives --require /Users/myk/Projects/spidernode/test/fixtures/cluster-preload.js cluster-preload-test.js
>invalid argument --expose_natives_as=v8natives
>/Users/myk/Projects/spidernode/out/Release/node: bad option: --expose_natives_as=v8natives
>
>    at exithandler (child_process.js:246:12)
>    at emitTwo (events.js:125:5)
>    at emit (events.js:213:7)
>    at maybeClose (internal/child_process.js:893:5)
>    at ChildProcess.prototype.spawn/< (internal/child_process.js:335:11)
>    at emitOne (events.js:115:5)
>    at emit (events.js:210:7)
>    at Socket.prototype._destroy/< (net.js:530:7)
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-preload.js
