### ISSUE TITLE
test-repl-harmony and test-repl-unexpected-token-recoverable throw: Error: child.stderr be silent

### ISSUE THREAD

**Issue by mykmelez** [mozilla/spidernode#274]
>=== release test-repl-harmony ===                           
>Path: parallel/test-repl-harmony
>/Users/myk/Projects/spidernode/test/parallel/test-repl-harmony.js:17
>
>
>Error: child.stderr be silent
>    at /Users/myk/Projects/spidernode/test/parallel/test-repl-harmony.js:17:9
>    at emitOne (events.js:96:5)
>    at emit (events.js:188:7)
>    at readableAddChunk (_stream_readable.js:176:11)
>    at Readable.prototype.push (_stream_readable.js:134:10)
>    at onread (net.js:543:15)
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-repl-harmony.js
>--- CRASHED (Signal: 11) ---
…
>=== release test-repl-unexpected-token-recoverable ===                    
>Path: parallel/test-repl-unexpected-token-recoverable
>/Users/myk/Projects/spidernode/test/parallel/test-repl-unexpected-token-recoverable.js:19
>
>
>Error: child.stderr be silent
>    at /Users/myk/Projects/spidernode/test/parallel/test-repl-unexpected-token-recoverable.js:19:9
>    at emitOne (events.js:96:5)
>    at emit (events.js:188:7)
>    at readableAddChunk (_stream_readable.js:176:11)
>    at Readable.prototype.push (_stream_readable.js:134:10)
>    at onread (net.js:543:15)
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-repl-unexpected-token-recoverable.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
Both of these tests still fail, but they now fail with different errors (different from the error they used to fail, and also different from each other). So I'm closing this issue and will open new separate issues for each test.
