### ISSUE TITLE
test-repl-tab-complete throws: SyntaxError: expected property name, got end of script

### ISSUE THREAD

**Issue by mykmelez** [mozilla/spidernode#276]
>=== release test-repl-tab-complete ===                             
>Path: parallel/test-repl-tab-complete
>JS warning at repl:3: expression closures are deprecated
>JS warning at repl:2: expression closures are deprecated
>JS warning at repl:4: expression closures are deprecated
>JS warning at repl:3: expression closures are deprecated
>JS error at <no filename>:0: uncaught exception: AssertionError: [ [], 'cus' ] deepStrictEqual [ [ 'custom' ], 'cus' ]
>
>:0
>
>
>AssertionError: [ [], 'cus' ] deepStrictEqual [ [ 'custom' ], 'cus' ]
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-repl-tab-complete.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
test-repl-tab-complete now throws `SyntaxError: expected property name, got end of script`:

>=== release test-repl-tab-complete ===                    
>Path: parallel/test-repl-tab-complete
>JS error at repl:2: SyntaxError: expected property name, got end of script
>repl:2
>
>
>SyntaxError: expected property name, got end of script
>    at createScript (vm.js:74:10)
>    at defaultEval (repl.js:194:18)
>    at bound (domain.js:301:11)
>    at runBound (domain.js:314:12)
>    at onLine (repl.js:433:5)
>    at emitOne (events.js:115:5)
>    at emit (events.js:210:7)
>    at Interface.prototype._onLine (readline.js:262:5)
>    at Interface.prototype._normalWrite (readline.js:405:7)
>    at ondata (readline.js:122:5)
>    at emitOne (events.js:115:5)
>    at emit (events.js:210:7)
>    at ArrayStream/this.run/< (/Users/myk/Projects/spidernode/test/common.js:530:7)
>    at ArrayStream/this.run (/Users/myk/Projects/spidernode/test/common.js:529:5)
>    at /Users/myk/Projects/spidernode/test/parallel/test-repl-tab-complete.js:52:1
>    at Module.prototype._compile (module.js:585:16)
>    at Module._extensions[".js"] (module.js:595:3)
>    at Module.prototype.load (module.js:503:3)
>    at tryModuleLoad (module.js:466:5)
>    at Module._load (module.js:458:3)
>    at Module.runMain (module.js:620:3)
>    at run (bootstrap_node.js:437:7)
>    at startup (bootstrap_node.js:147:9)
>    at bootstrap_node.js:552:3
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-repl-tab-complete.js
