### ISSUE TITLE
test-tick-processor complains: invalid argument --no_logfile_per_isolate, --logfile=-, --prof

### ISSUE THREAD

**Issue by mykmelez** [mozilla/spidernode#284]
The assertions vary across release/debug builds, however.

Here's release:

>=== release test-tick-processor ===                      
>Path: parallel/test-tick-processor
>/Users/myk/Projects/spidernode/out/Release/node[94247]: ../src/node.cc:4486:int node::Start(int, char **): Assertion `(argc) > (0)' failed.
> 1: node::Abort() [/Users/myk/Projects/spidernode/out/Release/node]
> 2: node::RunMicrotasks(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/myk/Projects/spidernode/out/Release/node]
> 3: node::Start(int, char**) [/Users/myk/Projects/spidernode/out/Release/node]
> 4: start [/usr/lib/system/libdyld.dylib]
>Redirecting call to abort() to mozalloc_abort
>
>JS error at <no filename>:0: uncaught exception: AssertionError: There should be a single log file.
>
>:0
>
>
>AssertionError: There should be a single log file.
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-tick-processor.js
>--- CRASHED (Signal: 11) ---

Here's debug:

>=== debug test-tick-processor ===                       
>Path: parallel/test-tick-processor
>Assertion failure: clasp != &ArrayObject::class_, at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/jsobj.cpp:632
>Command: out/Debug/node /Users/myk/Projects/spidernode/test/parallel/test-tick-processor.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
test-tick-processor is no more, instead there are three tests in the test/tick-processor/ directory, all of which fail with the complaints `invalid argument --no_logfile_per_isolate`, `invalid argument --logfile=-`, and `invalid argument --prof`:

>=== release test-tick-processor-builtin ===                    
>Path: tick-processor/test-tick-processor-builtin
>invalid argument --no_logfile_per_isolate
>invalid argument --logfile=-
>invalid argument --prof
>/Users/myk/Projects/spidernode/out/Release/node: bad option: --no_logfile_per_isolate
>/Users/myk/Projects/spidernode/out/Release/node: bad option: --logfile=-
>/Users/myk/Projects/spidernode/out/Release/node: bad option: --prof
>buffer.js:33
>
>
>
>TypeError: invalid arguments
>    at FastBuffer (buffer.js:33:5)
>    at fromString (buffer.js:240:12)
>    at Buffer.from (buffer.js:136:12)
>    at fs.writeFileSync (fs.js:1289:12)
>    at match (/Users/myk/Projects/spidernode/test/tick-processor/tick-processor-base.js:33:3)
>    at runTest/< (/Users/myk/Projects/spidernode/test/tick-processor/tick-processor-base.js:27:5)
>    at ontimeout (timers.js:407:5)
>    at tryOnTimeout (timers.js:271:5)
>    at listOnTimeout (timers.js:235:5)
>Command: out/Release/node /Users/myk/Projects/spidernode/test/tick-processor/test-tick-processor-builtin.js
>=== release test-tick-processor-cpp-core ===                    
>Path: tick-processor/test-tick-processor-cpp-core
>invalid argument --no_logfile_per_isolate
>invalid argument --logfile=-
>invalid argument --prof
>/Users/myk/Projects/spidernode/out/Release/node: bad option: --no_logfile_per_isolate
>/Users/myk/Projects/spidernode/out/Release/node: bad option: --logfile=-
>/Users/myk/Projects/spidernode/out/Release/node: bad option: --prof
>buffer.js:33
>
>
>
>TypeError: invalid arguments
>    at FastBuffer (buffer.js:33:5)
>    at fromString (buffer.js:240:12)
>    at Buffer.from (buffer.js:136:12)
>    at fs.writeFileSync (fs.js:1289:12)
>    at match (/Users/myk/Projects/spidernode/test/tick-processor/tick-processor-base.js:33:3)
>    at runTest/< (/Users/myk/Projects/spidernode/test/tick-processor/tick-processor-base.js:27:5)
>    at ontimeout (timers.js:407:5)
>    at tryOnTimeout (timers.js:271:5)
>    at listOnTimeout (timers.js:235:5)
>Command: out/Release/node /Users/myk/Projects/spidernode/test/tick-processor/test-tick-processor-cpp-core.js
>=== release test-tick-processor-unknown ===                    
>Path: tick-processor/test-tick-processor-unknown
>invalid argument --no_logfile_per_isolate
>invalid argument --logfile=-
>invalid argument --prof
>/Users/myk/Projects/spidernode/out/Release/node: bad option: --no_logfile_per_isolate
>/Users/myk/Projects/spidernode/out/Release/node: bad option: --logfile=-
>/Users/myk/Projects/spidernode/out/Release/node: bad option: --prof
>buffer.js:33
>
>
>
>TypeError: invalid arguments
>    at FastBuffer (buffer.js:33:5)
>    at fromString (buffer.js:240:12)
>    at Buffer.from (buffer.js:136:12)
>    at fs.writeFileSync (fs.js:1289:12)
>    at match (/Users/myk/Projects/spidernode/test/tick-processor/tick-processor-base.js:33:3)
>    at runTest/< (/Users/myk/Projects/spidernode/test/tick-processor/tick-processor-base.js:27:5)
>    at ontimeout (timers.js:407:5)
>    at tryOnTimeout (timers.js:271:5)
>    at listOnTimeout (timers.js:235:5)
>Command: out/Release/node /Users/myk/Projects/spidernode/test/tick-processor/test-tick-processor-unknown.js
