### ISSUE TITLE
test-v8-flags throws: ReferenceError: common is not defined

### ISSUE THREAD

**Issue by mykmelez** [mozilla/spidernode#297]
>=== release test-v8-flags ===                                
>Path: parallel/test-v8-flags
>JS error at /Users/myk/Projects/spidernode/test/parallel/test-v8-flags.js:1: SyntaxError: expected expression, got '%'
>/Users/myk/Projects/spidernode/test/parallel/test-v8-flags.js:1
>%_IsSmi(42)
>
>
>SyntaxError: expected expression, got '%'
>    at /Users/myk/Projects/spidernode/test/parallel/test-v8-flags.js:16:8
>    at Module.prototype._compile (module.js:560:16)
>    at Module._extensions[".js"] (module.js:569:3)
>    at Module.prototype.load (module.js:477:3)
>    at tryModuleLoad (module.js:436:5)
>    at Module._load (module.js:428:3)
>    at Module.runMain (module.js:594:3)
>    at run (bootstrap_node.js:382:7)
>    at startup (bootstrap_node.js:137:9)
>    at bootstrap_node.js:497:3
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-v8-flags.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
This now throws `ReferenceError: common is not defined`:

>=== release test-v8-flags ===                    
>Path: parallel/test-v8-flags
>JS error at /Users/myk/Projects/spidernode/test/parallel/test-v8-flags.js:7: ReferenceError: common is not defined
>/Users/myk/Projects/spidernode/test/parallel/test-v8-flags.js:7
>
>
>
>ReferenceError: common is not defined
>    at /Users/myk/Projects/spidernode/test/parallel/test-v8-flags.js:7:1
>    at Module.prototype._compile (module.js:585:16)
>    at Module._extensions[".js"] (module.js:595:3)
>    at Module.prototype.load (module.js:503:3)
>    at tryModuleLoad (module.js:466:5)
>    at Module._load (module.js:458:3)
>    at Module.runMain (module.js:620:3)
>    at run (bootstrap_node.js:437:7)
>    at startup (bootstrap_node.js:147:9)
>    at bootstrap_node.js:552:3
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-v8-flags.js
