### ISSUE TITLE
test-v8-stats throws: ReferenceError: common is not defined

### ISSUE THREAD

**Issue by mykmelez** [mozilla/spidernode#298]
>=== release test-v8-stats ===                    
>Path: parallel/test-v8-stats
>JS error at <no filename>:0: uncaught exception: AssertionError: [] deepStrictEqual [ 'code_space',
>  'large_object_space',
>  'map_space',
>  'new_space',
>  'old_space' ]
>
>:0
>
>
>AssertionError: [] deepStrictEqual [ 'code_space',
>  'large_object_space',
>  'map_space',
>  'new_space',
>  'old_space' ]
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-v8-stats.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
Like test-v8-flags in #297, this now throws `ReferenceError: common is not defined`:

>=== release test-v8-stats ===                    
>Path: parallel/test-v8-stats
>JS error at /Users/myk/Projects/spidernode/test/parallel/test-v8-stats.js:24: ReferenceError: common is not defined
>/Users/myk/Projects/spidernode/test/parallel/test-v8-stats.js:24
>
>
>
>ReferenceError: common is not defined
>    at /Users/myk/Projects/spidernode/test/parallel/test-v8-stats.js:24:1
>    at Module.prototype._compile (module.js:585:16)
>    at Module._extensions[".js"] (module.js:595:3)
>    at Module.prototype.load (module.js:503:3)
>    at tryModuleLoad (module.js:466:5)
>    at Module._load (module.js:458:3)
>    at Module.runMain (module.js:620:3)
>    at run (bootstrap_node.js:437:7)
>    at startup (bootstrap_node.js:147:9)
>    at bootstrap_node.js:552:3
>Command: out/Release/node /Users/myk/Projects/spidernode/test/parallel/test-v8-stats.js
