### ISSUE TITLE
test-fs-watch-file asserts: function should not have been called

### ISSUE THREAD

**Issue by mykmelez** [mozilla/spidernode#324]
>=== release test-fs-watch-file ===                                
>Path: pummel/test-fs-watch-file
>JS error at fs.js:1506: Error: "watchFile()" requires a listener function
>
>fs.js:1506
>
>
>Error: "watchFile()" requires a listener function
>    at fs.watchFile (fs.js:1506:11)
>    at /Users/myk/Projects/spidernode/test/pummel/test-fs-watch-file.js:41:7
>    at _tryBlock (assert.js:312:5)
>    at _throws (assert.js:331:12)
>    at assert.throws (assert.js:361:3)
>    at /Users/myk/Projects/spidernode/test/pummel/test-fs-watch-file.js:39:1
>    at Module.prototype._compile (module.js:560:16)
>    at Module._extensions[".js"] (module.js:569:3)
>    at Module.prototype.load (module.js:477:3)
>    at tryModuleLoad (module.js:436:5)
>    at Module._load (module.js:428:3)
>    at Module.runMain (module.js:594:3)
>    at run (bootstrap_node.js:382:7)
>    at startup (bootstrap_node.js:137:9)
>    at bootstrap_node.js:497:3
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/pummel/test-fs-watch-file.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
Now it asserts `function should not have been called`:

>=== release test-fs-watch-file ===                    
>Path: pummel/test-fs-watch-file
>:0
>
>
>AssertionError: function should not have been called
>Command: out/Release/node /Users/myk/Projects/spidernode/test/pummel/test-fs-watch-file.js
