### ISSUE TITLE
addons/symlinked-module/test throws: Error: Cannot find module '[path/to/project]/test/addons/symlinked-module/build/Release/binding.node'

### ISSUE THREAD

**Issue by mykmelez** [mozilla/spidernode#342]
>=== release test ===                     
>Path: addons/symlinked-module/test
>JS error at module.js:459: Error: Cannot find module '/Users/myk/Projects/spidernode/test/addons/symlinked-module/build/Release/binding.node'
>
>module.js:459
>
>
>Error: Cannot find module '/Users/myk/Projects/spidernode/test/addons/symlinked-module/build/Release/binding.node'
>    at Module._resolveFilename (module.js:459:15)
>    at Module._load (module.js:407:18)
>    at Module.prototype.require (module.js:487:10)
>    at require (internal/module.js:20:14)
>    at /Users/myk/Projects/spidernode/test/addons/symlinked-module/test.js:30:15
>    at /Users/myk/Projects/spidernode/test/addons/symlinked-module/test.js:29:1
>    at Module.prototype._compile (module.js:560:16)
>    at Module._extensions[".js"] (module.js:569:3)
>    at Module.prototype.load (module.js:477:3)
>    at tryModuleLoad (module.js:436:5)
>    at Module._load (module.js:428:3)
>    at Module.runMain (module.js:594:3)
>    at run (bootstrap_node.js:382:7)
>    at startup (bootstrap_node.js:137:9)
>    at bootstrap_node.js:497:3
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/addons/symlinked-module/test.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
This reminds me of #340, although the error message is somewhat different.
