### ISSUE TITLE
test-debugger-client throws: Error: timeout

### ISSUE THREAD

**Issue by mykmelez** [mozilla/spidernode#344]
>=== release test-debugger-client ===                            
>Path: debugger/test-debugger-client
>>>> new node process: 94987
>>>> starting debugger session
>got stderr data "Debugger listening on 127.0.0.1:12346\n"
>
>/Users/myk/Projects/spidernode/test/debugger/test-debugger-client.js:13
>
>
>Error: timeout
>    at /Users/myk/Projects/spidernode/test/debugger/test-debugger-client.js:13:9
>    at unrefdHandle (timers.js:462:3)
>Assertion failure: !joinable(), at /Users/myk/Projects/spidernode/deps/spidershim/spidermonkey/js/src/threading/Thread.h:122
>Command: out/Release/node /Users/myk/Projects/spidernode/test/debugger/test-debugger-client.js
>--- CRASHED (Signal: 11) ---

**Comment by mykmelez** [comment]
Probably the same failure, although there's also a new exception (`ReferenceError: common is not defined`, which I've seen in other test failures) being reported in the child process:

>=== release test-debugger-client ===                    
>Path: debugger/test-debugger-client
>got stderr data "(node:56802) [DEP0062] DeprecationWarning: node --debug is deprecated. Please use node --inspect instead.\n"
>got stderr data "Debugger listening on 127.0.0.1:12346\n"
>got stderr data "JS error at [eval]:1: ReferenceError: common is not defined\n"
>got stderr data "[eval]:1\n\n\n\nReferenceError: common is not defined\n    at [eval]:1:49\n    at Script.prototype.runInThisContext (vm.js:44:12)\n    at runInThisContext (vm.js:116:10)\n    at [eval]-wrapper:6:8\n    at Module.prototype._compile (module.js:585:16)\n    at evalScript (bootstrap_node.js:402:20)\n    at startup/< (bootstrap_node.js:120:11)\n    at run (bootstrap_node.js:437:7)\n    at startup (bootstrap_node.js:119:9)\n    at bootstrap_node.js:552:3\n"
>>>> connecting...
>…
>>>> connecting...
>
>/Users/myk/Projects/spidernode/test/debugger/test-debugger-client.js:34
>
>
>Error: timeout
>    at /Users/myk/Projects/spidernode/test/debugger/test-debugger-client.js:34:9
>    at ontimeout (timers.js:407:5)
>    at unrefdHandle (timers.js:513:5)
>Command: out/Release/node /Users/myk/Projects/spidernode/test/debugger/test-debugger-client.js
